const ArticlesConstants = {
  RECEIVED_ARTICLE: 'RECEIVED_ARTICLE',
  RECEIVED_ARTICLES: 'RECEIVED_ARTICLES',
  REMOVE_ARTICLE: 'REMOVE_ARTICLE',
  RECEIVED_ARTICLES_SEARCH: 'RECEIVED_ARTICLES_SEARCH'
};

module.exports = ArticlesConstants;
