const GroupsConstants = {
  RECEIVED_GROUP: 'RECEIVED_GROUP',
  RECEIVED_GROUPS: 'RECEIVED_GROUPS',
  REMOVE_GROUP: 'REMOVE_GROUP',
  RECEIVED_GROUPS_SEARCH: 'RECEIVED_GROUPS_SEARCH'
};

module.exports = GroupsConstants;
