const HighlightsConstants = {
  RECEIVED_HIGHLIGHT: "RECEIVED_HIGHLIGHT",
  RECEIVED_HIGHLIGHTS: "RECEIVED_HIGHLIGHTS",
  REMOVE_HIGHLIGHT: "REMOVE_HIGHLIGHT"
};

module.exports = HighlightsConstants;
